/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and maintained in source control so the
// TypeScript project is valid before the first local dev-server run.
